name: release build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - Android
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: unity-bumper-test/Library
          key: Library-unity-bumper-test-${{ matrix.targetPlatform }}
          restore-keys: Library-unity-bumper-test-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#          email: ${{ secrets.ALTSPACE_USERNAME }}
#          password: ${{ secrets.ALTSPACE_PASSWORD }}
          BuildTemplateScene: Assets\Scenes\SampleScene.unity
          targetFileName: template.zip
        with:
          projectPath: unity-bumper-test
          targetPlatform: ${{ matrix.targetPlatform }} 
          buildMethod: AltSpace_Unity_Uploader.AltspaceTemplateItem.buildAssetBundle
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
