name: release build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - Android
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: unity-bumper-test/Library
          key: Library-unity-bumper-test-${{ matrix.targetPlatform }}
          restore-keys: Library-unity-bumper-test-Target
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: unity-bumper-test
          targetPlatform: ${{ matrix.targetPlatform }} 
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Build/${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
