name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: unity-bumper-test
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: unity-bumper-test/Library
          key: Library-unity-bumper-test-Target
          restore-keys: Library-unity-bumper-test-Target          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts
